import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/lib/context/AuthProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <AuthProvider>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <header className="flex justify-center space-x-5">
                        <Link href="/">
                            Home
                        </Link>
                        <Link href="/login">
                            Login
                        </Link>
                        <Link href="/dashboard">
                            Dashboard
                        </Link>
                    </header>
                    <main className="flex-1">
                        {children}
                    </main>
                </body>
            </AuthProvider>
        </html>
    );
}
